apriltags:
  - id: 207
    x: 1.40
    y: 1.19
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 226
    x: 1.62
    y: 1.19
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 228
    x: 1.40
    y: 2.47
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0
  - id: 75
    x: 1.62
    y: 2.47
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0
  - id: 227
    x: 1.17
    y: 1.63
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0.5
  - id: 38
    x: 1.87
    y: 1.83
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0.5
  - id: 48
    x: 0.55
    y: 2.40
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0
  - id: 56
    x: 0.55
    y: 2.40
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0
  - id: 560
    x: 0.0
    y: 2.98
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 50
    x: 0.60
    y: 2.93
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0.5
  - id: 500
    x: 1.23
    y: 2.47
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: -0.5
  - id: 480
    x: 1.28
    y: 2.97
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 163
    x: 0.0
    y: 1.15
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 1630
    x: 2.00
    y: 0.0
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: -0.5
