apriltags:
  - id: 207
    x: 1.40
    y: 1.19
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 226
    x: 1.62
    y: 1.19
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 228
    x: 1.40
    y: 2.47
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0
  - id: 75
    x: 1.62
    y: 2.47
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0
  - id: 227
    x: 1.17
    y: 1.63
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0.5
